Improved test target.
git-svn-id: svn://svn.code.sf.net/p/brlcad/code/brlcad/trunk@4378 2f96ce8b-6d43-0410-b8df-bffccc660ffb

diff --git a/burst/Cakefile b/burst/Cakefile
--- a/burst/Cakefile
+++ b/burst/Cakefile
@@ -7,7 +7,7 @@
  *			Maryland 21005-5066
  *			(301)278-6651 or AV-298-6651
  *
- *	$Header: /usr/Backup/upgrade/brlcad/brlcad/burst/Cakefile,v 1.4 1990-08-22 09:40:20 moss Exp $ (BRL)
+ *	$Header: /usr/Backup/upgrade/brlcad/brlcad/burst/Cakefile,v 1.5 1990-08-28 16:49:25 moss Exp $ (BRL)
  *
  * FONTDIR is pathname to font file (times.r.6) which is included with sources
  * but on real BSD systems is found in /usr/lib/vfont.
@@ -25,6 +25,10 @@
 #include "../Cakefile.prog"
 
 /* Explicit composition of each product */
+PRODUCTS:	OBJ
+	CC LDFLAGS -o burst OBJ LIB_PRE''LIBRT RT_LIBES LIB_PRE''LIBFB LIBTERMLIB LIBES MYLIBES -ltermlib -lm
+
+all: MYLIBES PRODUCTS
 
 Hm/libHm.a:
 	cd Hm; make
@@ -35,10 +39,22 @@ Sc/libSc.a:
 Tc/libTc.a:
 	cd Tc; make
 
-PRODUCTS:	OBJ MYLIBES
-	CC LDFLAGS -o burst OBJ LIB_PRE''LIBRT RT_LIBES LIB_PRE''LIBFB LIBTERMLIB LIBES MYLIBES -ltermlib -lm
+test&:	PRODUCTS tfiles/ktank.g
+	./burst -b < tfiles/ktank.in
+	@if test $? -ne 0 \
+	then	echo "Test failed."; exit 1 \
+	fi
+	diff tfiles/ktank.burst tfiles/ktank.burst.bak
+	@if test $? -ne 0 \
+	then	echo "Test failed."; exit 1 \
+	fi
+	diff tfiles/ktank.shotlines tfiles/ktank.shotlines.bak
+	@if test $? -ne 0 \
+	then	echo "Test failed."; exit 1 \
+	fi
+	@echo "Tested OK."
 
-test&:	PRODUCTS
-	./burst < tfiles/ktank.in
+tfiles/ktank.g:
+	asc2g < tfiles/ktank.asc > tfiles/ktank.g
 
 #include "../Cakefile.rules"
